-- AlterTable
ALTER TABLE `KycRecord` MODIFY `status` ENUM('NONE', 'PENDING', 'APPROVING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `User` MODIFY `kycStatus` ENUM('NONE', 'PENDING', 'APPROVING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'NONE';
