-- AlterTable
ALTER TABLE `kycrecord` MODIFY `status` ENUM('NONE', 'PENDING', 'APPROVING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `user` MODIFY `kycStatus` ENUM('NONE', 'PENDING', 'APPROVING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'NONE';
